# Generated by Django 5.0.1 on 2024-02-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file_content',
            old_name='question',
            new_name='file_name',
        ),
        migrations.AlterField(
            model_name='pdf_file',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='date published'),
        ),
    ]
